# Optional choices generated by the LOSP setup wizard. This is loaded before
# any product inheritance so a persisted Vanilla selection takes effect early.
-include vendor/lineage/.losp_build_config.mk

# GMS is the LOSP default for configurations without a generated selection.
WITH_GMS ?= true
TARGET_INCLUDE_PIXEL_LAUNCHER ?= false

# Inherit mobile full common Lineage stuff
$(call inherit-product, vendor/lineage/config/common_mobile_full.mk)

# Enable support of one-handed mode
PRODUCT_PRODUCT_PROPERTIES += \
    ro.support_one_handed_mode?=true

$(call inherit-product, vendor/lineage/config/telephony.mk)

# Google Mobile Services
ifeq ($(WITH_GMS),true)
ifeq ($(TARGET_USES_MINI_GAPPS),true)
ifneq (,$(wildcard vendor/gms/gms_mini.mk))
$(call inherit-product, vendor/gms/gms_mini.mk)
else
$(error TARGET_USES_MINI_GAPPS is true, but vendor/gms/gms_mini.mk is unavailable)
endif
else ifeq ($(TARGET_USES_PICO_GAPPS),true)
ifneq (,$(wildcard vendor/gms/gms_pico.mk))
$(call inherit-product, vendor/gms/gms_pico.mk)
else
$(error TARGET_USES_PICO_GAPPS is true, but vendor/gms/gms_pico.mk is unavailable)
endif
else
$(call inherit-product, vendor/lineage/config/gms_full.mk)
endif
endif
